DropForce/DropforceV3/main/default/objects/Product2/fields/Manufacturer__c.field-meta.xml
<CustomField>
    <fullName>Manufacturer__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Manufacturer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

DropForce/force-app/main/default/objects/Product2/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Featured_Product__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

CodeforceAnnaBranch/force-app/main/default/classes/objectRenderListController.cls
public class objectRenderListController {

    @AuraEnabled
    public static List<sObject> fetchObj (String input, Integer limitV, Id manuId){

        if (input == 'FSupplier') {
            return [SELECT Id,PhotoUrl FROM Account WHERE FeaturedM__c != null AND Type = 'Manufacturer' LIMIT :limitV]; //featured Supplier
        } else if (input == 'FProduct') {
            return [SELECT DisplayUrl,Id FROM Product2 WHERE Product__c != null LIMIT :limitV]; // featured product
        } else if (input == 'Product') {
            return [SELECT DisplayUrl,Id FROM Product2 WHERE Manufacturer__c = :manuId LIMIT :limitV]; 
        } else {
            return [SELECT Id,PhotoUrl FROM Account WHERE FeaturedM__c != null AND Type = 'Manufacturer' LIMIT :limitV];
        }
    }

}